AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  PipelineBucketName:
    Type: String
    Description: 'The pattern of bucket names to allow access to read artifacts from.  Recommended
      value: *'
Description: Lambda function to run cfn_nag as a step in a pipeline
Metadata:
  AWS::ServerlessRepo::Application:
    Name: cfn-nag-pipeline
    Description: A lambda function to run cfn_nag as an action in CodePipeline
    Author: Stelligent
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE.md
    ReadmeUrl: README.md
    Labels: ['codepipeline','cloudformation','cfn_nag']
    HomePageUrl: https://github.com/stelligent/cfn-nag-pipeline
    SemanticVersion: 0.0.1
    SourceCodeUrl: https://github.com/stelligent/cfn-nag-pipeline
Resources:
  CfnNagFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - Statement:
        - Action:
          - codepipeline:PutJobSuccessResult
          - codepipeline:PutJobFailureResult
          Resource:
          - Fn::Sub: arn:${AWS::Partition}:codepipeline:${AWS::Region}:${AWS::AccountId}:*
          Effect: Allow
      - Statement:
        - Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:GetBucketLocation
          - s3:GetObjectVersion
          - s3:GetLifecycleConfiguration
          Resource:
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}
            - bucketName:
                Ref: PipelineBucketName
          - Fn::Sub:
            - arn:${AWS::Partition}:s3:::${bucketName}/*
            - bucketName:
                Ref: PipelineBucketName
          Effect: Allow
      Handler: JRubyHandlerWrapper
      FunctionName: cfn-nag-pipeline
      Timeout: 300
      CodeUri:
        Bucket: sardeployments
        Key: cfn-nag-pipeline.jar
      Runtime: java8
      MemorySize: 1024
Transform: AWS::Serverless-2016-10-31